###################################################################################################################                                                                                                   #
# * OpenPit - An Open Source implementation of "The Pit" MiniGame
# * This plugin requires PlaceholderAPI and ZNPCs, but will work without them.
#
# PLACEHOLDERS:
#        %thepit_name% - displays the player's name
#        %thepit_stat% - returns wether or not the player is in combat.
#        %thepit_date% - returns the current date in the format day/month/year
#        %thepit_gold% - shows how much currency the player has (NOT VAULT SUPPORTED)
# 
# * Permissions and commands can be found on the plugin page or by typing /openpit help in-game
#
# * Credits:
#         - This plugin is built on classes from discontinued "The Pit" Plugins
#         - The AutoRespawn Function is built on classes from a discontinued AutoRespawn Plugin
#         - "Shop" and "Perks" NPCs are built on ZNPCs
###################################################################################################################
CombatTag:
  Duration: 5 #How long the combat tag lasts before the player is set to "idling" again
Econ-Enabled: true
Events:
  - 'QUICKMATHS'
#Find a list of materials here: 
Gold:
  Amount: 1 #Amount of gold that drops
  Material: GOLD_INGOT #Material that drops.
  Intervals-In-Seconds: 20
 #Titles and actionbar settings for when the player dies. Set to " " if you do not want that section.
Titles:
  Enabled: false
  Actionbar: ' '
  Levelup-Subtitle: '&7%old_level% → %thepit_level%'
  Levelup-Title: '&b&lLEVEL UP!' #Title shown when a player's level upgrades
Levels:
  Exp: 16
#Change the default chat format. Set Enabled to false if you have another custom plugin such as EssentialsChat
#which modifies the chat.
ChatFormat:
  Enabled: true
  Format: '&f%thepit_level% &7%thepit_name% : %message%'
  Nametag: '%thepit_level% '
#Header and footer on the tablist.
Tablist:
  Header: '&bYou are playing on &e&lMC.EXAMPLE.NET'
  Footer: '&ARanks, Boosters & MORE! &c&lSTORE.EXAMPLE.NET'
#Every message sent in-game by ThePit.
Messages:
  Fighting: '&cCombat' #Shown on scoreboard when player enters combat
  Idle: '&aIdle' # Shown on scoreboard when player leaves combat
  EventLog: '&6Event' # Shown on scoreboard when an event is triggered
  Unknown: '&cUnknown Command. Type /openpit for help'
  Reload: '&aConfig reloaded.'
  Levelup: '&aYou have leveled up.'
  Respawn: '&aYou have respawned.'
  NoPermission: '&cNo permission to use this command!'
  Help: #Not reccomended to change for future reference.
    - '&7----------------&c&l[OpenPit]&7----------------'
    - '&c/openpit - &7Displays this help message'
    - '&c/openpit goldstart - &7Starts spawning gold.'
    - '&c/openpit reload - &7Reloads the config'
    - '&c/openpit kills - &7Creates hologram of kill stats. '
    - '&c/openpit stats - &7Shows gui of player stats.'
    - '&c/openpit respawn - &7Teleports the player to spawn'
    - '&c/openpit perks - &7Display perks based on prestige.'
    - '&c/openpit perks - &7Display the Shop'
    - '&c/openpit stats - &7GUI of player statistics'
    - '&c/openpit spawnshop <Player> <Amount> - &7Built in economy'
    - '&c/openpit spawnperks - &7Spawn Perks NPC'
    - '&c/openpit giveitem <Enchantment> &7Gives a mystic wells item with that enchantment'
    - '&c/gold setloc - &7Set Gold Spawn Location'
    - '&c/protect - &7Protect the Spawn Area'

#Events that run every x minutes
Events:
  Start-Message: '&aAN EVENT STARTED!'
  Holo-String: '&eEvent Running!'
  Types:
    QuickMaths:
      Enabled: true
      Message: 'QUICK MATHS HAS STARTED! %f% + %s%'
Blocked-Worlds: #Worlds that the pit is disabled in.
  - 'blockedworld'
Tags:
 Default:
  Color: '&d'
 MVP:
  Color: '&d'
 Vip:
  Color: '&6' 
EnchantmentTypes: #All enchantments added by the mystic well.

#PANTS ENCHANTMENTS

  BOOBOO:
    Lore: #Lore added to item when enchantment applied.
    - ' '
    - '&9Boo-boo'
    - '&7Passively regain &c1❤  &7every 5'
    - '&7Seconds'
  CREATIVE:
    Lore:
    - ' '
    - '&9Creative'
    - '&7Spawn with &b16 planks&7. Wood remains for'
    - '&730 seconds. Gain &b+6 blocks &7on kill.' 
  CRICKET:
    Lore:
    - ' '
    - '&9Cricket'
    - '&7 Receive &9-7% &7damage when you or your'
    - '&7victim are standing on grass.' 
  DANGERCLOSE:
    Lore:
    - ' '
    - '&9Danger Close'
    - '&7Gain &eSpeed III &7(6s) when'
    - '&7reaching &c4❤ &7(10s cooldown)'
  EGGS:
    Lore:
    - ' '
    - '&9Eggs'
    - '&7Spawn with &b8 eggs.'
    - '&7Gain &b+8 eggs &7on kill.'
  ELECTROLYTES:
    Lore:
    - ' '
    - '&9Electrolytes'
    - '&7If you have &9Speed &7on kill, add &c2 &7seconds'
    - '&7to its duration, (Halved for Speed II+, Max 18s).'
  HEARTS:
    Lore:
    - ' '
    - '&9Hearts'
    - '&7Increase your max health by 0.5❤.' 
  TNT:
    Lore:
    - ' '
    - '&9TNT'
    - '&7Spawn with &c2 TNT&7. &cTNT'
    - '&7explodes after 1.5 seconds and' 
    - '&7deals &c1.5❤ &7in a 3 blocks radius.'
    - '&7Gain &c+2 TNT&7 on kill.'
  STRIKEGOLD:
    Lore:
    - ' '
    - '&9Strike Gold'
    - '&7Increase your max health by 0.5❤.'
  DOUBLEJUMP:
    Lore: 
    - ' '
    - '&dRARE! &9Double Jump'
    - '&7 You can double-jump. (20s cooldown).'
  ESCAPEPOD:
    Lore:
    - ' '
    - '&dRARE! &9Escape Pod'
    - '&7When hit below &c2❤&7, launch into the air dealing'
    - '&c1❤ &7damage to nearby enemies and gaining Regen III (20s).'
    - '&7Can launch once per life.'

# Come here to change some plugin data, rest of the data is stored in data.yml
Top:
  Example:
    Kills: 1
# All blocks with an inventory or any blocks that when right clicked shouldn't equip armor. 
# - Curtousy of ArmorEquipEvent Library.
blocked:
    - FURNACE
    - CHEST
    - TRAPPED_CHEST
    - BEACON
    - DISPENSER
    - DROPPER
    - HOPPER
    - WORKBENCH
    - ENCHANTMENT_TABLE
    - ENDER_CHEST
    - ANVIL
    - BED_BLOCK
    - FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - ACACIA_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - IRON_DOOR_BLOCK
    - WOODEN_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - WOOD_BUTTON
    - STONE_BUTTON
    - TRAP_DOOR
    - IRON_TRAPDOOR
    - DIODE_BLOCK_OFF
    - DIODE_BLOCK_ON
    - REDSTONE_COMPARATOR_OFF
    - REDSTONE_COMPARATOR_ON
    - FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - DARK_OAK_FENCE
    - ACACIA_FENCE
    - NETHER_FENCE
    - BREWING_STAND
    - CAULDRON
    - SIGN_POST
    - WALL_SIGN
    - SIGN
    - LEVER
    - BLACK_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - LIME_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PINK_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - RED_SHULKER_BOX
    - SILVER_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - YELLOW_SHULKER_BOX